# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1179, 973)
        MainWindow.setWindowTitle("SCRN2")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/gui/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setText("")
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setMinimumSize(QtCore.QSize(200, 0))
        self.stop_button.setMaximumSize(QtCore.QSize(300, 16777215))
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_2.addWidget(self.stop_button)
        self.right_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.right_tab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_tab.sizePolicy().hasHeightForWidth())
        self.right_tab.setSizePolicy(sizePolicy)
        self.right_tab.setMinimumSize(QtCore.QSize(200, 0))
        self.right_tab.setMaximumSize(QtCore.QSize(300, 550))
        self.right_tab.setUsesScrollButtons(True)
        self.right_tab.setDocumentMode(False)
        self.right_tab.setTabsClosable(False)
        self.right_tab.setMovable(False)
        self.right_tab.setObjectName("right_tab")
        self.spectra_tab = QtWidgets.QWidget()
        self.spectra_tab.setEnabled(True)
        self.spectra_tab.setObjectName("spectra_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.spectra_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.live_button = QtWidgets.QPushButton(self.spectra_tab)
        self.live_button.setMinimumSize(QtCore.QSize(0, 25))
        self.live_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.live_button.setObjectName("live_button")
        self.gridLayout_8.addWidget(self.live_button, 0, 0, 1, 1)
        self.single_button = QtWidgets.QPushButton(self.spectra_tab)
        self.single_button.setObjectName("single_button")
        self.gridLayout_8.addWidget(self.single_button, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)
        self.line = QtWidgets.QFrame(self.spectra_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.mode_combobox = QtWidgets.QComboBox(self.spectra_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mode_combobox.sizePolicy().hasHeightForWidth())
        self.mode_combobox.setSizePolicy(sizePolicy)
        self.mode_combobox.setMinimumSize(QtCore.QSize(0, 25))
        self.mode_combobox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.mode_combobox.setObjectName("mode_combobox")
        self.verticalLayout.addWidget(self.mode_combobox)
        self.line_8 = QtWidgets.QFrame(self.spectra_tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.dark_button = QtWidgets.QPushButton(self.spectra_tab)
        self.dark_button.setMinimumSize(QtCore.QSize(0, 25))
        self.dark_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.dark_button.setObjectName("dark_button")
        self.verticalLayout.addWidget(self.dark_button)
        self.bg_button = QtWidgets.QPushButton(self.spectra_tab)
        self.bg_button.setMinimumSize(QtCore.QSize(0, 25))
        self.bg_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bg_button.setObjectName("bg_button")
        self.verticalLayout.addWidget(self.bg_button)
        self.ref_button = QtWidgets.QPushButton(self.spectra_tab)
        self.ref_button.setMinimumSize(QtCore.QSize(0, 25))
        self.ref_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.ref_button.setObjectName("ref_button")
        self.verticalLayout.addWidget(self.ref_button)
        self.line_2 = QtWidgets.QFrame(self.spectra_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.mean_button = QtWidgets.QPushButton(self.spectra_tab)
        self.mean_button.setMinimumSize(QtCore.QSize(0, 25))
        self.mean_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.mean_button.setObjectName("mean_button")
        self.verticalLayout.addWidget(self.mean_button)
        self.series_button = QtWidgets.QPushButton(self.spectra_tab)
        self.series_button.setMinimumSize(QtCore.QSize(0, 25))
        self.series_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.series_button.setObjectName("series_button")
        self.verticalLayout.addWidget(self.series_button)
        self.line_3 = QtWidgets.QFrame(self.spectra_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.savespectra_button = QtWidgets.QPushButton(self.spectra_tab)
        self.savespectra_button.setMinimumSize(QtCore.QSize(0, 25))
        self.savespectra_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.savespectra_button.setObjectName("savespectra_button")
        self.verticalLayout.addWidget(self.savespectra_button)
        self.save_button = QtWidgets.QPushButton(self.spectra_tab)
        self.save_button.setMinimumSize(QtCore.QSize(0, 25))
        self.save_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.line_4 = QtWidgets.QFrame(self.spectra_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.loaddark_button = QtWidgets.QPushButton(self.spectra_tab)
        self.loaddark_button.setMinimumSize(QtCore.QSize(0, 25))
        self.loaddark_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.loaddark_button.setObjectName("loaddark_button")
        self.verticalLayout.addWidget(self.loaddark_button)
        self.loadlamp_button = QtWidgets.QPushButton(self.spectra_tab)
        self.loadlamp_button.setMinimumSize(QtCore.QSize(0, 25))
        self.loadlamp_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.loadlamp_button.setObjectName("loadlamp_button")
        self.verticalLayout.addWidget(self.loadlamp_button)
        self.loadbg_button = QtWidgets.QPushButton(self.spectra_tab)
        self.loadbg_button.setMinimumSize(QtCore.QSize(0, 25))
        self.loadbg_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.loadbg_button.setObjectName("loadbg_button")
        self.verticalLayout.addWidget(self.loadbg_button)
        self.line_5 = QtWidgets.QFrame(self.spectra_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.reset_button = QtWidgets.QPushButton(self.spectra_tab)
        self.reset_button.setMinimumSize(QtCore.QSize(0, 25))
        self.reset_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout.addWidget(self.reset_button)
        self.line_6 = QtWidgets.QFrame(self.spectra_tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.right_tab.addTab(self.spectra_tab, "")
        self.scanning_tab = QtWidgets.QWidget()
        self.scanning_tab.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanning_tab.sizePolicy().hasHeightForWidth())
        self.scanning_tab.setSizePolicy(sizePolicy)
        self.scanning_tab.setObjectName("scanning_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scanning_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addpos_button = QtWidgets.QPushButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addpos_button.sizePolicy().hasHeightForWidth())
        self.addpos_button.setSizePolicy(sizePolicy)
        self.addpos_button.setMinimumSize(QtCore.QSize(0, 25))
        self.addpos_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.addpos_button.setObjectName("addpos_button")
        self.verticalLayout_3.addWidget(self.addpos_button)
        self.spangrid_button = QtWidgets.QPushButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spangrid_button.sizePolicy().hasHeightForWidth())
        self.spangrid_button.setSizePolicy(sizePolicy)
        self.spangrid_button.setMinimumSize(QtCore.QSize(0, 25))
        self.spangrid_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.spangrid_button.setObjectName("spangrid_button")
        self.verticalLayout_3.addWidget(self.spangrid_button)
        self.searchgrid_button = QtWidgets.QPushButton(self.scanning_tab)
        self.searchgrid_button.setEnabled(False)
        self.searchgrid_button.setMinimumSize(QtCore.QSize(0, 25))
        self.searchgrid_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.searchgrid_button.setObjectName("searchgrid_button")
        self.verticalLayout_3.addWidget(self.searchgrid_button)
        self.lockin_checkBox = QtWidgets.QCheckBox(self.scanning_tab)
        self.lockin_checkBox.setEnabled(False)
        self.lockin_checkBox.setObjectName("lockin_checkBox")
        self.verticalLayout_3.addWidget(self.lockin_checkBox)
        self.search_checkBox = QtWidgets.QCheckBox(self.scanning_tab)
        self.search_checkBox.setEnabled(False)
        self.search_checkBox.setObjectName("search_checkBox")
        self.verticalLayout_3.addWidget(self.search_checkBox)
        self.line_7 = QtWidgets.QFrame(self.scanning_tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.label_5 = QtWidgets.QLabel(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_button = QtWidgets.QToolButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setMinimumSize(QtCore.QSize(26, 26))
        self.add_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/gui/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon1)
        self.add_button.setCheckable(False)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_3.addWidget(self.add_button)
        self.remove_button = QtWidgets.QToolButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_button.sizePolicy().hasHeightForWidth())
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setMinimumSize(QtCore.QSize(26, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/gui/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_button.setIcon(icon2)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_3.addWidget(self.remove_button)
        self.clear_button = QtWidgets.QToolButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setMinimumSize(QtCore.QSize(26, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/gui/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_button.setIcon(icon3)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_3.addWidget(self.clear_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.posTable = QtWidgets.QTableView(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posTable.sizePolicy().hasHeightForWidth())
        self.posTable.setSizePolicy(sizePolicy)
        self.posTable.setMinimumSize(QtCore.QSize(0, 140))
        self.posTable.setMaximumSize(QtCore.QSize(16777215, 2000))
        self.posTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.posTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.posTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.posTable.setAlternatingRowColors(True)
        self.posTable.setObjectName("posTable")
        self.posTable.horizontalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.posTable)
        self.scan_button = QtWidgets.QPushButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_button.sizePolicy().hasHeightForWidth())
        self.scan_button.setSizePolicy(sizePolicy)
        self.scan_button.setMinimumSize(QtCore.QSize(0, 25))
        self.scan_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.scan_button.setObjectName("scan_button")
        self.verticalLayout_3.addWidget(self.scan_button)
        self.addpos_button.raise_()
        self.spangrid_button.raise_()
        self.searchgrid_button.raise_()
        self.lockin_checkBox.raise_()
        self.search_checkBox.raise_()
        self.label_5.raise_()
        self.line_7.raise_()
        self.posTable.raise_()
        self.scan_button.raise_()
        self.right_tab.addTab(self.scanning_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.settings_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.integration_time_spin = QtWidgets.QDoubleSpinBox(self.settings_tab)
        self.integration_time_spin.setMinimumSize(QtCore.QSize(25, 0))
        self.integration_time_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.integration_time_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.integration_time_spin.setMinimum(0.1)
        self.integration_time_spin.setMaximum(1000.0)
        self.integration_time_spin.setSingleStep(0.1)
        self.integration_time_spin.setProperty("value", 0.2)
        self.integration_time_spin.setObjectName("integration_time_spin")
        self.horizontalLayout_4.addWidget(self.integration_time_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.settings_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.number_of_samples_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.number_of_samples_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.number_of_samples_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.number_of_samples_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.number_of_samples_spin.setMinimum(1)
        self.number_of_samples_spin.setMaximum(10000)
        self.number_of_samples_spin.setProperty("value", 1)
        self.number_of_samples_spin.setObjectName("number_of_samples_spin")
        self.horizontalLayout_5.addWidget(self.number_of_samples_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.settings_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.slitwidth_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.slitwidth_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.slitwidth_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.slitwidth_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slitwidth_spin.setMinimum(10)
        self.slitwidth_spin.setMaximum(2500)
        self.slitwidth_spin.setSingleStep(10)
        self.slitwidth_spin.setProperty("value", 50)
        self.slitwidth_spin.setObjectName("slitwidth_spin")
        self.horizontalLayout_6.addWidget(self.slitwidth_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.settings_tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.centre_wavelength_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.centre_wavelength_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.centre_wavelength_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.centre_wavelength_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.centre_wavelength_spin.setMinimum(0)
        self.centre_wavelength_spin.setMaximum(3000)
        self.centre_wavelength_spin.setSingleStep(10)
        self.centre_wavelength_spin.setProperty("value", 650)
        self.centre_wavelength_spin.setObjectName("centre_wavelength_spin")
        self.horizontalLayout_8.addWidget(self.centre_wavelength_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.settings_tab)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_18.addWidget(self.label_7)
        self.grating_combobox = QtWidgets.QComboBox(self.settings_tab)
        self.grating_combobox.setMinimumSize(QtCore.QSize(0, 25))
        self.grating_combobox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.grating_combobox.setObjectName("grating_combobox")
        self.horizontalLayout_18.addWidget(self.grating_combobox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.line_10 = QtWidgets.QFrame(self.settings_tab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_4.addWidget(self.line_10)
        self.label_8 = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.settings_tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.search_int_time_spin = QtWidgets.QDoubleSpinBox(self.settings_tab)
        self.search_int_time_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.search_int_time_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.search_int_time_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_int_time_spin.setMinimum(0.05)
        self.search_int_time_spin.setMaximum(100.0)
        self.search_int_time_spin.setSingleStep(0.1)
        self.search_int_time_spin.setProperty("value", 0.1)
        self.search_int_time_spin.setObjectName("search_int_time_spin")
        self.horizontalLayout_9.addWidget(self.search_int_time_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.settings_tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.rasterdim_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.rasterdim_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.rasterdim_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.rasterdim_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rasterdim_spin.setMinimum(1)
        self.rasterdim_spin.setMaximum(500)
        self.rasterdim_spin.setProperty("value", 20)
        self.rasterdim_spin.setObjectName("rasterdim_spin")
        self.horizontalLayout_10.addWidget(self.rasterdim_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.settings_tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.rasterwidth_spin = QtWidgets.QDoubleSpinBox(self.settings_tab)
        self.rasterwidth_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.rasterwidth_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.rasterwidth_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rasterwidth_spin.setMinimum(0.5)
        self.rasterwidth_spin.setMaximum(20.0)
        self.rasterwidth_spin.setSingleStep(0.1)
        self.rasterwidth_spin.setProperty("value", 1.2)
        self.rasterwidth_spin.setObjectName("rasterwidth_spin")
        self.horizontalLayout_11.addWidget(self.rasterwidth_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.settings_tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.sigma_spin = QtWidgets.QDoubleSpinBox(self.settings_tab)
        self.sigma_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.sigma_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.sigma_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sigma_spin.setMinimum(0.1)
        self.sigma_spin.setMaximum(10.0)
        self.sigma_spin.setSingleStep(0.1)
        self.sigma_spin.setProperty("value", 1.0)
        self.sigma_spin.setObjectName("sigma_spin")
        self.horizontalLayout_12.addWidget(self.sigma_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.settings_tab)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.search_zmult_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.search_zmult_spin.setMaximumSize(QtCore.QSize(120, 35))
        self.search_zmult_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_zmult_spin.setMinimum(1)
        self.search_zmult_spin.setMaximum(10)
        self.search_zmult_spin.setProperty("value", 3)
        self.search_zmult_spin.setObjectName("search_zmult_spin")
        self.horizontalLayout_17.addWidget(self.search_zmult_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.search_correct_checkBox = QtWidgets.QCheckBox(self.settings_tab)
        self.search_correct_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.search_correct_checkBox.setMaximumSize(QtCore.QSize(16777215, 35))
        self.search_correct_checkBox.setObjectName("search_correct_checkBox")
        self.verticalLayout_4.addWidget(self.search_correct_checkBox)
        self.savesettings_button = QtWidgets.QPushButton(self.settings_tab)
        self.savesettings_button.setObjectName("savesettings_button")
        self.verticalLayout_4.addWidget(self.savesettings_button)
        self.right_tab.addTab(self.settings_tab, "")
        self.scan3d_tab = QtWidgets.QWidget()
        self.scan3d_tab.setObjectName("scan3d_tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scan3d_tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_15 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.cube_width_label = QtWidgets.QLabel(self.scan3d_tab)
        self.cube_width_label.setMinimumSize(QtCore.QSize(0, 20))
        self.cube_width_label.setObjectName("cube_width_label")
        self.horizontalLayout_19.addWidget(self.cube_width_label)
        self.cube_width_spin = QtWidgets.QDoubleSpinBox(self.scan3d_tab)
        self.cube_width_spin.setMinimumSize(QtCore.QSize(0, 20))
        self.cube_width_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cube_width_spin.setMaximum(100.0)
        self.cube_width_spin.setProperty("value", 2.0)
        self.cube_width_spin.setObjectName("cube_width_spin")
        self.horizontalLayout_19.addWidget(self.cube_width_spin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.cube_steps_spin = QtWidgets.QSpinBox(self.scan3d_tab)
        self.cube_steps_spin.setMinimumSize(QtCore.QSize(0, 20))
        self.cube_steps_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cube_steps_spin.setMaximum(10000)
        self.cube_steps_spin.setProperty("value", 10)
        self.cube_steps_spin.setObjectName("cube_steps_spin")
        self.horizontalLayout_20.addWidget(self.cube_steps_spin)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.scan3d_button = QtWidgets.QPushButton(self.scan3d_tab)
        self.scan3d_button.setMinimumSize(QtCore.QSize(0, 25))
        self.scan3d_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.scan3d_button.setObjectName("scan3d_button")
        self.verticalLayout_5.addWidget(self.scan3d_button)
        self.line_11 = QtWidgets.QFrame(self.scan3d_tab)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_5.addWidget(self.line_11)
        self.label_20 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_5.addWidget(self.label_20)
        self.zcorrection_checkbox = QtWidgets.QCheckBox(self.scan3d_tab)
        self.zcorrection_checkbox.setObjectName("zcorrection_checkbox")
        self.verticalLayout_5.addWidget(self.zcorrection_checkbox)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_18 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_16.addWidget(self.label_18)
        self.zcorrection_spinbox = QtWidgets.QSpinBox(self.scan3d_tab)
        self.zcorrection_spinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zcorrection_spinbox.setMinimum(-90)
        self.zcorrection_spinbox.setMaximum(90)
        self.zcorrection_spinbox.setObjectName("zcorrection_spinbox")
        self.horizontalLayout_16.addWidget(self.zcorrection_spinbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        self.line_13 = QtWidgets.QFrame(self.scan3d_tab)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_5.addWidget(self.line_13)
        self.label_21 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.lockin_button = QtWidgets.QPushButton(self.scan3d_tab)
        self.lockin_button.setEnabled(True)
        self.lockin_button.setMinimumSize(QtCore.QSize(0, 25))
        self.lockin_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.lockin_button.setObjectName("lockin_button")
        self.verticalLayout_5.addWidget(self.lockin_button)
        self.line_15 = QtWidgets.QFrame(self.scan3d_tab)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_5.addWidget(self.line_15)
        self.label_22 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.autofocus_combobox = QtWidgets.QComboBox(self.scan3d_tab)
        self.autofocus_combobox.setObjectName("autofocus_combobox")
        self.autofocus_combobox.addItem("")
        self.autofocus_combobox.addItem("")
        self.autofocus_combobox.addItem("")
        self.autofocus_combobox.addItem("")
        self.autofocus_combobox.addItem("")
        self.autofocus_combobox.addItem("")
        self.verticalLayout_5.addWidget(self.autofocus_combobox)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.zscan_centre_spinbox = QtWidgets.QSpinBox(self.scan3d_tab)
        self.zscan_centre_spinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zscan_centre_spinbox.setMinimum(400)
        self.zscan_centre_spinbox.setMaximum(1000)
        self.zscan_centre_spinbox.setSingleStep(10)
        self.zscan_centre_spinbox.setProperty("value", 600)
        self.zscan_centre_spinbox.setObjectName("zscan_centre_spinbox")
        self.horizontalLayout_21.addWidget(self.zscan_centre_spinbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_25 = QtWidgets.QLabel(self.scan3d_tab)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_23.addWidget(self.label_25)
        self.zscan_width_spinbox = QtWidgets.QSpinBox(self.scan3d_tab)
        self.zscan_width_spinbox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zscan_width_spinbox.setMinimum(10)
        self.zscan_width_spinbox.setMaximum(1000)
        self.zscan_width_spinbox.setSingleStep(10)
        self.zscan_width_spinbox.setProperty("value", 10)
        self.zscan_width_spinbox.setObjectName("zscan_width_spinbox")
        self.horizontalLayout_23.addWidget(self.zscan_width_spinbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_23)
        self.line_9 = QtWidgets.QFrame(self.scan3d_tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_5.addWidget(self.line_9)
        self.offset_button = QtWidgets.QPushButton(self.scan3d_tab)
        self.offset_button.setObjectName("offset_button")
        self.verticalLayout_5.addWidget(self.offset_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.right_tab.addTab(self.scan3d_tab, "")
        self.verticalLayout_2.addWidget(self.right_tab)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.temp_button = QtWidgets.QPushButton(self.centralwidget)
        self.temp_button.setMinimumSize(QtCore.QSize(0, 25))
        self.temp_button.setMaximumSize(QtCore.QSize(300, 35))
        self.temp_button.setObjectName("temp_button")
        self.verticalLayout_2.addWidget(self.temp_button)
        self.label_temp = QtWidgets.QLabel(self.centralwidget)
        self.label_temp.setObjectName("label_temp")
        self.verticalLayout_2.addWidget(self.label_temp)
        self.autofocus_button = QtWidgets.QPushButton(self.centralwidget)
        self.autofocus_button.setEnabled(False)
        self.autofocus_button.setMinimumSize(QtCore.QSize(300, 25))
        self.autofocus_button.setMaximumSize(QtCore.QSize(10, 35))
        self.autofocus_button.setObjectName("autofocus_button")
        self.verticalLayout_2.addWidget(self.autofocus_button)
        self.searchmax_button = QtWidgets.QPushButton(self.centralwidget)
        self.searchmax_button.setEnabled(False)
        self.searchmax_button.setMinimumSize(QtCore.QSize(0, 25))
        self.searchmax_button.setMaximumSize(QtCore.QSize(300, 35))
        self.searchmax_button.setObjectName("searchmax_button")
        self.verticalLayout_2.addWidget(self.searchmax_button)
        self.correct_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.correct_checkBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.correct_checkBox.setObjectName("correct_checkBox")
        self.verticalLayout_2.addWidget(self.correct_checkBox)
        self.label_step_size = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step_size.sizePolicy().hasHeightForWidth())
        self.label_step_size.setSizePolicy(sizePolicy)
        self.label_step_size.setMinimumSize(QtCore.QSize(0, 15))
        self.label_step_size.setMaximumSize(QtCore.QSize(300, 15))
        self.label_step_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step_size.setObjectName("label_step_size")
        self.verticalLayout_2.addWidget(self.label_step_size)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(-1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stepup_button = QtWidgets.QPushButton(self.frame_2)
        self.stepup_button.setMinimumSize(QtCore.QSize(30, 25))
        self.stepup_button.setMaximumSize(QtCore.QSize(100, 35))
        self.stepup_button.setObjectName("stepup_button")
        self.horizontalLayout_14.addWidget(self.stepup_button)
        self.label_stepsize = QtWidgets.QLabel(self.frame_2)
        self.label_stepsize.setMinimumSize(QtCore.QSize(30, 0))
        self.label_stepsize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_stepsize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stepsize.setObjectName("label_stepsize")
        self.horizontalLayout_14.addWidget(self.label_stepsize)
        self.stepdown_button = QtWidgets.QPushButton(self.frame_2)
        self.stepdown_button.setMinimumSize(QtCore.QSize(30, 25))
        self.stepdown_button.setMaximumSize(QtCore.QSize(100, 35))
        self.stepdown_button.setObjectName("stepdown_button")
        self.horizontalLayout_14.addWidget(self.stepdown_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.stage_frame = QtWidgets.QFrame(self.centralwidget)
        self.stage_frame.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_frame.sizePolicy().hasHeightForWidth())
        self.stage_frame.setSizePolicy(sizePolicy)
        self.stage_frame.setMinimumSize(QtCore.QSize(100, 90))
        self.stage_frame.setMaximumSize(QtCore.QSize(300, 200))
        self.stage_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stage_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stage_frame.setObjectName("stage_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stage_frame)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.zdown_button = QtWidgets.QPushButton(self.stage_frame)
        self.zdown_button.setMaximumSize(QtCore.QSize(40, 50))
        self.zdown_button.setObjectName("zdown_button")
        self.gridLayout_2.addWidget(self.zdown_button, 2, 4, 1, 1)
        self.xup_button = QtWidgets.QPushButton(self.stage_frame)
        self.xup_button.setMaximumSize(QtCore.QSize(40, 50))
        self.xup_button.setObjectName("xup_button")
        self.gridLayout_2.addWidget(self.xup_button, 1, 0, 1, 1)
        self.ydown_button = QtWidgets.QPushButton(self.stage_frame)
        self.ydown_button.setMaximumSize(QtCore.QSize(40, 50))
        self.ydown_button.setObjectName("ydown_button")
        self.gridLayout_2.addWidget(self.ydown_button, 2, 1, 1, 1)
        self.xdown_button = QtWidgets.QPushButton(self.stage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xdown_button.sizePolicy().hasHeightForWidth())
        self.xdown_button.setSizePolicy(sizePolicy)
        self.xdown_button.setMaximumSize(QtCore.QSize(40, 50))
        self.xdown_button.setObjectName("xdown_button")
        self.gridLayout_2.addWidget(self.xdown_button, 1, 2, 1, 1)
        self.zup_button = QtWidgets.QPushButton(self.stage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zup_button.sizePolicy().hasHeightForWidth())
        self.zup_button.setSizePolicy(sizePolicy)
        self.zup_button.setMaximumSize(QtCore.QSize(40, 50))
        self.zup_button.setObjectName("zup_button")
        self.gridLayout_2.addWidget(self.zup_button, 0, 4, 1, 1)
        self.yup_button = QtWidgets.QPushButton(self.stage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yup_button.sizePolicy().hasHeightForWidth())
        self.yup_button.setSizePolicy(sizePolicy)
        self.yup_button.setMaximumSize(QtCore.QSize(40, 50))
        self.yup_button.setObjectName("yup_button")
        self.gridLayout_2.addWidget(self.yup_button, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.stage_frame)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_x.sizePolicy().hasHeightForWidth())
        self.label_x.setSizePolicy(sizePolicy)
        self.label_x.setMinimumSize(QtCore.QSize(30, 0))
        self.label_x.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_13.addWidget(self.label_x)
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_y.sizePolicy().hasHeightForWidth())
        self.label_y.setSizePolicy(sizePolicy)
        self.label_y.setMinimumSize(QtCore.QSize(30, 0))
        self.label_y.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_13.addWidget(self.label_y)
        self.label_z = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_z.sizePolicy().hasHeightForWidth())
        self.label_z.setSizePolicy(sizePolicy)
        self.label_z.setMinimumSize(QtCore.QSize(30, 0))
        self.label_z.setMaximumSize(QtCore.QSize(100, 300))
        self.label_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_z.setObjectName("label_z")
        self.horizontalLayout_13.addWidget(self.label_z)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 2, 1)
        self.left_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.left_tab.setEnabled(True)
        self.left_tab.setObjectName("left_tab")
        self.spec_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spec_tab.sizePolicy().hasHeightForWidth())
        self.spec_tab.setSizePolicy(sizePolicy)
        self.spec_tab.setObjectName("spec_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.spec_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.specwidget = QtWidgets.QWidget(self.spec_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specwidget.sizePolicy().hasHeightForWidth())
        self.specwidget.setSizePolicy(sizePolicy)
        self.specwidget.setObjectName("specwidget")
        self.horizontalLayout.addWidget(self.specwidget)
        self.left_tab.addTab(self.spec_tab, "")
        self.cam_tab = QtWidgets.QWidget()
        self.cam_tab.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_tab.sizePolicy().hasHeightForWidth())
        self.cam_tab.setSizePolicy(sizePolicy)
        self.cam_tab.setObjectName("cam_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.cam_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.camwidget = QtWidgets.QWidget(self.cam_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camwidget.sizePolicy().hasHeightForWidth())
        self.camwidget.setSizePolicy(sizePolicy)
        self.camwidget.setObjectName("camwidget")
        self.gridLayout_6.addWidget(self.camwidget, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.camreference_button = QtWidgets.QPushButton(self.cam_tab)
        self.camreference_button.setMinimumSize(QtCore.QSize(0, 25))
        self.camreference_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.camreference_button.setObjectName("camreference_button")
        self.gridLayout_7.addWidget(self.camreference_button, 1, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.cam_tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.exposure_time_spin = QtWidgets.QSpinBox(self.cam_tab)
        self.exposure_time_spin.setMinimumSize(QtCore.QSize(100, 25))
        self.exposure_time_spin.setMaximumSize(QtCore.QSize(200, 35))
        self.exposure_time_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exposure_time_spin.setMinimum(1)
        self.exposure_time_spin.setMaximum(10000)
        self.exposure_time_spin.setSingleStep(10)
        self.exposure_time_spin.setProperty("value", 300)
        self.exposure_time_spin.setObjectName("exposure_time_spin")
        self.horizontalLayout_7.addWidget(self.exposure_time_spin)
        self.gridLayout_7.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.clear_reference_button = QtWidgets.QPushButton(self.cam_tab)
        self.clear_reference_button.setMinimumSize(QtCore.QSize(0, 25))
        self.clear_reference_button.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clear_reference_button.setObjectName("clear_reference_button")
        self.gridLayout_7.addWidget(self.clear_reference_button, 1, 2, 1, 1)
        self.autocontrast_checkBox = QtWidgets.QCheckBox(self.cam_tab)
        self.autocontrast_checkBox.setObjectName("autocontrast_checkBox")
        self.gridLayout_7.addWidget(self.autocontrast_checkBox, 0, 2, 1, 1)
        self.save_cam_image_button = QtWidgets.QPushButton(self.cam_tab)
        self.save_cam_image_button.setObjectName("save_cam_image_button")
        self.gridLayout_7.addWidget(self.save_cam_image_button, 1, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.left_tab.addTab(self.cam_tab, "")
        self.detector_tab = QtWidgets.QWidget()
        self.detector_tab.setObjectName("detector_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.detector_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.detectorwidget = QtWidgets.QWidget(self.detector_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detectorwidget.sizePolicy().hasHeightForWidth())
        self.detectorwidget.setSizePolicy(sizePolicy)
        self.detectorwidget.setObjectName("detectorwidget")
        self.gridLayout_3.addWidget(self.detectorwidget, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.correct_image_checkBox = QtWidgets.QCheckBox(self.detector_tab)
        self.correct_image_checkBox.setObjectName("correct_image_checkBox")
        self.gridLayout_5.addWidget(self.correct_image_checkBox, 0, 1, 1, 1)
        self.use_background_image_button = QtWidgets.QPushButton(self.detector_tab)
        self.use_background_image_button.setObjectName("use_background_image_button")
        self.gridLayout_5.addWidget(self.use_background_image_button, 0, 0, 1, 1)
        self.save_detectorimage_button = QtWidgets.QPushButton(self.detector_tab)
        self.save_detectorimage_button.setObjectName("save_detectorimage_button")
        self.gridLayout_5.addWidget(self.save_detectorimage_button, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.left_tab.addTab(self.detector_tab, "")
        self.gridLayout.addWidget(self.left_tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.right_tab.setCurrentIndex(0)
        self.left_tab.setCurrentIndex(0)
        self.scan_button.clicked.connect(MainWindow.on_start_scan_clicked)
        self.stop_button.clicked.connect(MainWindow.on_stop_clicked)
        self.reset_button.clicked.connect(MainWindow.on_reset_clicked)
        self.live_button.clicked.connect(MainWindow.on_live_clicked)
        self.searchgrid_button.clicked.connect(MainWindow.on_searchgrid_clicked)
        self.searchmax_button.clicked.connect(MainWindow.on_search_clicked)
        self.savespectra_button.clicked.connect(MainWindow.on_save_clicked)
        self.save_button.clicked.connect(MainWindow.on_saveas_clicked)
        self.dark_button.clicked.connect(MainWindow.on_dark_clicked)
        self.ref_button.clicked.connect(MainWindow.on_lamp_clicked)
        self.mean_button.clicked.connect(MainWindow.on_mean_clicked)
        self.bg_button.clicked.connect(MainWindow.on_bg_clicked)
        self.series_button.clicked.connect(MainWindow.on_series_clicked)
        self.loaddark_button.clicked.connect(MainWindow.on_loaddark_clicked)
        self.loadlamp_button.clicked.connect(MainWindow.on_loadlamp_clicked)
        self.loadbg_button.clicked.connect(MainWindow.on_loadbg_clicked)
        self.number_of_samples_spin.editingFinished.connect(MainWindow.on_number_of_samples_edited)
        self.slitwidth_spin.editingFinished.connect(MainWindow.on_slit_width_edited)
        self.grating_combobox.activated['int'].connect(MainWindow.on_grating_changed)
        self.centre_wavelength_spin.editingFinished.connect(MainWindow.on_centre_wavelength_edited)
        self.exposure_time_spin.editingFinished.connect(MainWindow.on_exposure_time_edited)
        self.rasterdim_spin.editingFinished.connect(MainWindow.on_rasterdim_edited)
        self.rasterwidth_spin.editingFinished.connect(MainWindow.on_rasterwidth_edited)
        self.sigma_spin.editingFinished.connect(MainWindow.on_sigma_edited)
        self.addpos_button.clicked.connect(MainWindow.on_addpos_clicked)
        self.spangrid_button.clicked.connect(MainWindow.on_spangrid_clicked)
        self.add_button.clicked.connect(MainWindow.on_scan_add)
        self.remove_button.clicked.connect(MainWindow.on_scan_remove)
        self.clear_button.clicked.connect(MainWindow.on_scan_clear)
        self.stepup_button.clicked.connect(MainWindow.on_stepup_clicked)
        self.stepdown_button.clicked.connect(MainWindow.on_stepdown_clicked)
        self.xup_button.clicked.connect(MainWindow.on_xup_clicked)
        self.xdown_button.clicked.connect(MainWindow.on_xdown_clicked)
        self.yup_button.clicked.connect(MainWindow.on_yup_clicked)
        self.ydown_button.clicked.connect(MainWindow.on_ydown_clicked)
        self.zup_button.clicked.connect(MainWindow.on_zup_clicked)
        self.zdown_button.clicked.connect(MainWindow.on_zdown_clicked)
        self.mode_combobox.currentIndexChanged['int'].connect(MainWindow.on_mode_changed)
        self.left_tab.currentChanged['int'].connect(MainWindow.on_lefttab_changed)
        self.integration_time_spin.editingFinished.connect(MainWindow.on_int_time_edited)
        self.savesettings_button.clicked.connect(MainWindow.on_savesettings_clicked)
        self.temp_button.clicked.connect(MainWindow.on_temp_clicked)
        self.lockin_button.clicked.connect(MainWindow.on_lockin_clicked)
        self.search_int_time_spin.editingFinished.connect(MainWindow.on_search_int_time_edited)
        self.scan3d_button.clicked.connect(MainWindow.on_scan3d_clicked)
        self.camreference_button.clicked.connect(MainWindow.on_camreference_clicked)
        self.clear_reference_button.clicked.connect(MainWindow.on_clear_reference_clicked)
        self.zcorrection_spinbox.editingFinished.connect(MainWindow.on_z_correction_angle_edited)
        self.zcorrection_checkbox.clicked.connect(MainWindow.on_z_correction_angle_edited)
        self.search_zmult_spin.editingFinished.connect(MainWindow.on_search_zmult_edited)
        self.autofocus_button.clicked.connect(MainWindow.on_autofocus_clicked)
        self.search_correct_checkBox.toggled['bool'].connect(MainWindow.on_search_corrected_toggled)
        self.autofocus_combobox.currentIndexChanged['int'].connect(MainWindow.on_af_mode_changed)
        self.use_background_image_button.clicked.connect(MainWindow.on_use_image_background_clicked)
        self.save_detectorimage_button.clicked.connect(MainWindow.on_save_detectorimage_clicked)
        self.single_button.clicked.connect(MainWindow.on_single_clicked)
        self.offset_button.clicked.connect(MainWindow.on_offset_clicked)
        self.zscan_centre_spinbox.editingFinished.connect(MainWindow.on_zscan_centre_edited)
        self.zscan_width_spinbox.editingFinished.connect(MainWindow.on_zscan_width_edited)
        self.save_cam_image_button.clicked.connect(MainWindow.on_save_cam_image_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.live_button.setText(_translate("MainWindow", "Liveview"))
        self.single_button.setText(_translate("MainWindow", "Single"))
        self.dark_button.setText(_translate("MainWindow", "Take Dark Spectrum"))
        self.bg_button.setText(_translate("MainWindow", "Take Background Spectrum"))
        self.ref_button.setText(_translate("MainWindow", "Take Reference Spectrum"))
        self.mean_button.setText(_translate("MainWindow", "Take Mean Spectrum"))
        self.series_button.setText(_translate("MainWindow", "Take Time Series"))
        self.savespectra_button.setText(_translate("MainWindow", "Save All Spectra"))
        self.save_button.setText(_translate("MainWindow", "Save Mean spectrum as"))
        self.loaddark_button.setText(_translate("MainWindow", "Load Dark Spectrum"))
        self.loadlamp_button.setText(_translate("MainWindow", "Load Lamp Spectrum"))
        self.loadbg_button.setText(_translate("MainWindow", "Load Background Spectrum"))
        self.reset_button.setText(_translate("MainWindow", "Reset Internal Data"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.spectra_tab), _translate("MainWindow", "Spectra"))
        self.addpos_button.setText(_translate("MainWindow", "Add Position to List"))
        self.spangrid_button.setText(_translate("MainWindow", "Span Grid"))
        self.searchgrid_button.setText(_translate("MainWindow", "Search Max Grid"))
        self.lockin_checkBox.setText(_translate("MainWindow", "with Lock-In"))
        self.search_checkBox.setText(_translate("MainWindow", "with Search & Autofocus"))
        self.label_5.setText(_translate("MainWindow", "Scanning Positions"))
        self.remove_button.setText(_translate("MainWindow", "-"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        self.scan_button.setText(_translate("MainWindow", "Start Scan"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.scanning_tab), _translate("MainWindow", "Scanning"))
        self.label.setText(_translate("MainWindow", "Spectrometer Settings"))
        self.label_2.setText(_translate("MainWindow", "Integration Time [s]"))
        self.label_3.setText(_translate("MainWindow", "Number of Samples"))
        self.label_4.setText(_translate("MainWindow", "Slit Width [um]"))
        self.label_6.setText(_translate("MainWindow", "Centre Wavelength [nm]"))
        self.label_7.setText(_translate("MainWindow", "Choose Grating:"))
        self.label_8.setText(_translate("MainWindow", "Search Max Settings"))
        self.label_11.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_12.setText(_translate("MainWindow", "Raster Dimension [steps]"))
        self.label_13.setText(_translate("MainWindow", "Raster width [um]"))
        self.label_14.setText(_translate("MainWindow", "Starting Sigma [um]"))
        self.label_19.setText(_translate("MainWindow", "z multiplier"))
        self.search_correct_checkBox.setText(_translate("MainWindow", "Use Spectra Correction for Search"))
        self.savesettings_button.setText(_translate("MainWindow", "Save Settings"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.label_15.setText(_translate("MainWindow", "3D Scan"))
        self.cube_width_label.setText(_translate("MainWindow", "Scan Cube Width [um]:"))
        self.label_16.setText(_translate("MainWindow", "Scan Steps along Axis:"))
        self.scan3d_button.setText(_translate("MainWindow", "Scan"))
        self.label_20.setText(_translate("MainWindow", "Advanced Stage Settings"))
        self.zcorrection_checkbox.setText(_translate("MainWindow", "Correct z Movement for Angled Sample"))
        self.label_18.setText(_translate("MainWindow", "Sample Angle [°]:"))
        self.label_21.setText(_translate("MainWindow", "Advanced Spectrometer Settings"))
        self.lockin_button.setText(_translate("MainWindow", "Take Lockin Spectrum"))
        self.label_22.setText(_translate("MainWindow", "Autofocus Mode:"))
        self.autofocus_combobox.setItemText(0, _translate("MainWindow", "Gauss-Fit"))
        self.autofocus_combobox.setItemText(1, _translate("MainWindow", "Gauss Export Data"))
        self.autofocus_combobox.setItemText(2, _translate("MainWindow", "Maximum"))
        self.autofocus_combobox.setItemText(3, _translate("MainWindow", "Bright-field"))
        self.autofocus_combobox.setItemText(4, _translate("MainWindow", "Z-scan"))
        self.autofocus_combobox.setItemText(5, _translate("MainWindow", "Gauss Width"))
        self.label_23.setText(_translate("MainWindow", "Z-Scan Centre [nm]:"))
        self.label_25.setText(_translate("MainWindow", "Z-Scan Width [nm]:"))
        self.offset_button.setText(_translate("MainWindow", "Set Offsets"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.scan3d_tab), _translate("MainWindow", "Misc"))
        self.temp_button.setText(_translate("MainWindow", "Update Detector Temperature"))
        self.label_temp.setText(_translate("MainWindow", "Detector Temperature:"))
        self.autofocus_button.setText(_translate("MainWindow", "Autofocus"))
        self.searchmax_button.setText(_translate("MainWindow", "Search Maximum x/y"))
        self.correct_checkBox.setText(_translate("MainWindow", "Correct Spectrum"))
        self.label_step_size.setText(_translate("MainWindow", "Set Step Size [um]"))
        self.stepup_button.setText(_translate("MainWindow", "+"))
        self.label_stepsize.setText(_translate("MainWindow", "1.0"))
        self.stepdown_button.setText(_translate("MainWindow", "-"))
        self.zdown_button.setText(_translate("MainWindow", "z-"))
        self.xup_button.setText(_translate("MainWindow", "x+"))
        self.ydown_button.setText(_translate("MainWindow", "y-"))
        self.xdown_button.setText(_translate("MainWindow", "x-"))
        self.zup_button.setText(_translate("MainWindow", "z+"))
        self.yup_button.setText(_translate("MainWindow", "y+"))
        self.label_x.setText(_translate("MainWindow", "X: 10.0"))
        self.label_y.setText(_translate("MainWindow", "Y: 10.0"))
        self.label_z.setText(_translate("MainWindow", "Z: 10.0"))
        self.left_tab.setTabText(self.left_tab.indexOf(self.spec_tab), _translate("MainWindow", "Spectrometer"))
        self.camreference_button.setText(_translate("MainWindow", "Take Camera Reference Image"))
        self.label_10.setText(_translate("MainWindow", "Exposure time [ms]"))
        self.clear_reference_button.setText(_translate("MainWindow", "Clear Reference Image"))
        self.autocontrast_checkBox.setText(_translate("MainWindow", "Enable Auto Contrast"))
        self.save_cam_image_button.setText(_translate("MainWindow", "Save Image"))
        self.left_tab.setTabText(self.left_tab.indexOf(self.cam_tab), _translate("MainWindow", "Camera"))
        self.correct_image_checkBox.setText(_translate("MainWindow", "Correct Image"))
        self.use_background_image_button.setText(_translate("MainWindow", "Use Last Image as Background"))
        self.save_detectorimage_button.setText(_translate("MainWindow", "Save"))
        self.left_tab.setTabText(self.left_tab.indexOf(self.detector_tab), _translate("MainWindow", "Detector"))

import resources_rc
