# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 963)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/gui/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.left_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.left_tab.setEnabled(True)
        self.left_tab.setObjectName("left_tab")
        self.spec_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spec_tab.sizePolicy().hasHeightForWidth())
        self.spec_tab.setSizePolicy(sizePolicy)
        self.spec_tab.setObjectName("spec_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.spec_tab)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.specwidget = QtWidgets.QWidget(self.spec_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specwidget.sizePolicy().hasHeightForWidth())
        self.specwidget.setSizePolicy(sizePolicy)
        self.specwidget.setObjectName("specwidget")
        self.horizontalLayout.addWidget(self.specwidget)
        self.left_tab.addTab(self.spec_tab, "")
        self.cam_tab = QtWidgets.QWidget()
        self.cam_tab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_tab.sizePolicy().hasHeightForWidth())
        self.cam_tab.setSizePolicy(sizePolicy)
        self.cam_tab.setObjectName("cam_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.cam_tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.camwidget = QtWidgets.QWidget(self.cam_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camwidget.sizePolicy().hasHeightForWidth())
        self.camwidget.setSizePolicy(sizePolicy)
        self.camwidget.setObjectName("camwidget")
        self.horizontalLayout_2.addWidget(self.camwidget)
        self.left_tab.addTab(self.cam_tab, "")
        self.gridLayout.addWidget(self.left_tab, 0, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setText("")
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 2, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setEnabled(False)
        self.stop_button.setMinimumSize(QtCore.QSize(200, 0))
        self.stop_button.setMaximumSize(QtCore.QSize(300, 16777215))
        self.stop_button.setObjectName("stop_button")
        self.verticalLayout_2.addWidget(self.stop_button)
        self.right_tab = QtWidgets.QTabWidget(self.centralwidget)
        self.right_tab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_tab.sizePolicy().hasHeightForWidth())
        self.right_tab.setSizePolicy(sizePolicy)
        self.right_tab.setMinimumSize(QtCore.QSize(200, 0))
        self.right_tab.setMaximumSize(QtCore.QSize(300, 16777215))
        self.right_tab.setUsesScrollButtons(True)
        self.right_tab.setDocumentMode(False)
        self.right_tab.setTabsClosable(False)
        self.right_tab.setMovable(False)
        self.right_tab.setObjectName("right_tab")
        self.spectra_tab = QtWidgets.QWidget()
        self.spectra_tab.setEnabled(True)
        self.spectra_tab.setObjectName("spectra_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.spectra_tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.live_button = QtWidgets.QPushButton(self.spectra_tab)
        self.live_button.setObjectName("live_button")
        self.verticalLayout.addWidget(self.live_button)
        self.line = QtWidgets.QFrame(self.spectra_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.livedetector_button = QtWidgets.QPushButton(self.spectra_tab)
        self.livedetector_button.setObjectName("livedetector_button")
        self.verticalLayout.addWidget(self.livedetector_button)
        self.line_8 = QtWidgets.QFrame(self.spectra_tab)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.dark_button = QtWidgets.QPushButton(self.spectra_tab)
        self.dark_button.setObjectName("dark_button")
        self.verticalLayout.addWidget(self.dark_button)
        self.bg_button = QtWidgets.QPushButton(self.spectra_tab)
        self.bg_button.setObjectName("bg_button")
        self.verticalLayout.addWidget(self.bg_button)
        self.ref_button = QtWidgets.QPushButton(self.spectra_tab)
        self.ref_button.setObjectName("ref_button")
        self.verticalLayout.addWidget(self.ref_button)
        self.line_2 = QtWidgets.QFrame(self.spectra_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.mean_button = QtWidgets.QPushButton(self.spectra_tab)
        self.mean_button.setObjectName("mean_button")
        self.verticalLayout.addWidget(self.mean_button)
        self.series_button = QtWidgets.QPushButton(self.spectra_tab)
        self.series_button.setObjectName("series_button")
        self.verticalLayout.addWidget(self.series_button)
        self.line_3 = QtWidgets.QFrame(self.spectra_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.savespectra_button = QtWidgets.QPushButton(self.spectra_tab)
        self.savespectra_button.setObjectName("savespectra_button")
        self.verticalLayout.addWidget(self.savespectra_button)
        self.save_button = QtWidgets.QPushButton(self.spectra_tab)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.line_4 = QtWidgets.QFrame(self.spectra_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.loaddark_button = QtWidgets.QPushButton(self.spectra_tab)
        self.loaddark_button.setObjectName("loaddark_button")
        self.verticalLayout.addWidget(self.loaddark_button)
        self.loadlamp_button = QtWidgets.QPushButton(self.spectra_tab)
        self.loadlamp_button.setObjectName("loadlamp_button")
        self.verticalLayout.addWidget(self.loadlamp_button)
        self.loadbg_button = QtWidgets.QPushButton(self.spectra_tab)
        self.loadbg_button.setObjectName("loadbg_button")
        self.verticalLayout.addWidget(self.loadbg_button)
        self.line_5 = QtWidgets.QFrame(self.spectra_tab)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.reset_button = QtWidgets.QPushButton(self.spectra_tab)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout.addWidget(self.reset_button)
        self.line_6 = QtWidgets.QFrame(self.spectra_tab)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.right_tab.addTab(self.spectra_tab, "")
        self.scanning_tab = QtWidgets.QWidget()
        self.scanning_tab.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanning_tab.sizePolicy().hasHeightForWidth())
        self.scanning_tab.setSizePolicy(sizePolicy)
        self.scanning_tab.setObjectName("scanning_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scanning_tab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addpos_button = QtWidgets.QPushButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addpos_button.sizePolicy().hasHeightForWidth())
        self.addpos_button.setSizePolicy(sizePolicy)
        self.addpos_button.setObjectName("addpos_button")
        self.verticalLayout_3.addWidget(self.addpos_button)
        self.spangrid_button = QtWidgets.QPushButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spangrid_button.sizePolicy().hasHeightForWidth())
        self.spangrid_button.setSizePolicy(sizePolicy)
        self.spangrid_button.setObjectName("spangrid_button")
        self.verticalLayout_3.addWidget(self.spangrid_button)
        self.searchgrid_button = QtWidgets.QPushButton(self.scanning_tab)
        self.searchgrid_button.setEnabled(False)
        self.searchgrid_button.setObjectName("searchgrid_button")
        self.verticalLayout_3.addWidget(self.searchgrid_button)
        self.lockin_checkBox = QtWidgets.QCheckBox(self.scanning_tab)
        self.lockin_checkBox.setEnabled(False)
        self.lockin_checkBox.setObjectName("lockin_checkBox")
        self.verticalLayout_3.addWidget(self.lockin_checkBox)
        self.search_checkBox = QtWidgets.QCheckBox(self.scanning_tab)
        self.search_checkBox.setEnabled(False)
        self.search_checkBox.setObjectName("search_checkBox")
        self.verticalLayout_3.addWidget(self.search_checkBox)
        self.line_7 = QtWidgets.QFrame(self.scanning_tab)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_3.addWidget(self.line_7)
        self.label_5 = QtWidgets.QLabel(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.frame = QtWidgets.QFrame(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 35))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 271, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_button = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setMinimumSize(QtCore.QSize(26, 26))
        self.add_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/gui/list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_button.setIcon(icon1)
        self.add_button.setCheckable(False)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout_3.addWidget(self.add_button)
        self.remove_button = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_button.sizePolicy().hasHeightForWidth())
        self.remove_button.setSizePolicy(sizePolicy)
        self.remove_button.setMinimumSize(QtCore.QSize(26, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/gui/list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_button.setIcon(icon2)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout_3.addWidget(self.remove_button)
        self.clear_button = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_button.sizePolicy().hasHeightForWidth())
        self.clear_button.setSizePolicy(sizePolicy)
        self.clear_button.setMinimumSize(QtCore.QSize(26, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/gui/edit-delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_button.setIcon(icon3)
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_3.addWidget(self.clear_button)
        self.verticalLayout_3.addWidget(self.frame)
        self.posTable = QtWidgets.QTableView(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posTable.sizePolicy().hasHeightForWidth())
        self.posTable.setSizePolicy(sizePolicy)
        self.posTable.setMinimumSize(QtCore.QSize(0, 150))
        self.posTable.setMaximumSize(QtCore.QSize(16777215, 2000))
        self.posTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.posTable.setAlternatingRowColors(True)
        self.posTable.setObjectName("posTable")
        self.posTable.horizontalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.posTable)
        self.scan_button = QtWidgets.QPushButton(self.scanning_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_button.sizePolicy().hasHeightForWidth())
        self.scan_button.setSizePolicy(sizePolicy)
        self.scan_button.setObjectName("scan_button")
        self.verticalLayout_3.addWidget(self.scan_button)
        self.addpos_button.raise_()
        self.spangrid_button.raise_()
        self.searchgrid_button.raise_()
        self.lockin_checkBox.raise_()
        self.search_checkBox.raise_()
        self.label_5.raise_()
        self.line_7.raise_()
        self.frame.raise_()
        self.posTable.raise_()
        self.scan_button.raise_()
        self.right_tab.addTab(self.scanning_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.settings_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.integration_time_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.integration_time_spin.setMinimumSize(QtCore.QSize(30, 25))
        self.integration_time_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.integration_time_spin.setWrapping(False)
        self.integration_time_spin.setFrame(True)
        self.integration_time_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.integration_time_spin.setProperty("showGroupSeparator", False)
        self.integration_time_spin.setMinimum(10)
        self.integration_time_spin.setMaximum(10000)
        self.integration_time_spin.setSingleStep(10)
        self.integration_time_spin.setProperty("value", 200)
        self.integration_time_spin.setObjectName("integration_time_spin")
        self.horizontalLayout_4.addWidget(self.integration_time_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.settings_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.number_of_samples_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.number_of_samples_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.number_of_samples_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.number_of_samples_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.number_of_samples_spin.setMinimum(1)
        self.number_of_samples_spin.setMaximum(10000)
        self.number_of_samples_spin.setProperty("value", 1)
        self.number_of_samples_spin.setObjectName("number_of_samples_spin")
        self.horizontalLayout_5.addWidget(self.number_of_samples_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.settings_tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.slitwidth_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.slitwidth_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.slitwidth_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.slitwidth_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.slitwidth_spin.setMinimum(10)
        self.slitwidth_spin.setMaximum(2500)
        self.slitwidth_spin.setSingleStep(10)
        self.slitwidth_spin.setProperty("value", 50)
        self.slitwidth_spin.setObjectName("slitwidth_spin")
        self.horizontalLayout_6.addWidget(self.slitwidth_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.settings_tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.centre_wavelength_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.centre_wavelength_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.centre_wavelength_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.centre_wavelength_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.centre_wavelength_spin.setMinimum(0)
        self.centre_wavelength_spin.setMaximum(3000)
        self.centre_wavelength_spin.setSingleStep(10)
        self.centre_wavelength_spin.setProperty("value", 650)
        self.centre_wavelength_spin.setObjectName("centre_wavelength_spin")
        self.horizontalLayout_8.addWidget(self.centre_wavelength_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.label_7 = QtWidgets.QLabel(self.settings_tab)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.grating_combobox = QtWidgets.QComboBox(self.settings_tab)
        self.grating_combobox.setMinimumSize(QtCore.QSize(0, 25))
        self.grating_combobox.setObjectName("grating_combobox")
        self.verticalLayout_4.addWidget(self.grating_combobox)
        self.label_15 = QtWidgets.QLabel(self.settings_tab)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setObjectName("label_15")
        self.verticalLayout_4.addWidget(self.label_15)
        self.image_combobox = QtWidgets.QComboBox(self.settings_tab)
        self.image_combobox.setEditable(False)
        self.image_combobox.setObjectName("image_combobox")
        self.verticalLayout_4.addWidget(self.image_combobox)
        self.line_10 = QtWidgets.QFrame(self.settings_tab)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_4.addWidget(self.line_10)
        self.label_9 = QtWidgets.QLabel(self.settings_tab)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.settings_tab)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.exposure_time_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.exposure_time_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.exposure_time_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.exposure_time_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.exposure_time_spin.setMinimum(1)
        self.exposure_time_spin.setMaximum(10000)
        self.exposure_time_spin.setSingleStep(10)
        self.exposure_time_spin.setProperty("value", 300)
        self.exposure_time_spin.setObjectName("exposure_time_spin")
        self.horizontalLayout_7.addWidget(self.exposure_time_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line_9 = QtWidgets.QFrame(self.settings_tab)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_4.addWidget(self.line_9)
        self.label_8 = QtWidgets.QLabel(self.settings_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.settings_tab)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.search_int_time_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.search_int_time_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.search_int_time_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.search_int_time_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_int_time_spin.setMinimum(10)
        self.search_int_time_spin.setMaximum(10000)
        self.search_int_time_spin.setProperty("value", 300)
        self.search_int_time_spin.setObjectName("search_int_time_spin")
        self.horizontalLayout_9.addWidget(self.search_int_time_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.settings_tab)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.rasterdim_spin = QtWidgets.QSpinBox(self.settings_tab)
        self.rasterdim_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.rasterdim_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rasterdim_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rasterdim_spin.setMinimum(1)
        self.rasterdim_spin.setMaximum(500)
        self.rasterdim_spin.setProperty("value", 20)
        self.rasterdim_spin.setObjectName("rasterdim_spin")
        self.horizontalLayout_10.addWidget(self.rasterdim_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.settings_tab)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.rasterwidth_spin = QtWidgets.QDoubleSpinBox(self.settings_tab)
        self.rasterwidth_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.rasterwidth_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rasterwidth_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rasterwidth_spin.setMinimum(0.5)
        self.rasterwidth_spin.setMaximum(20.0)
        self.rasterwidth_spin.setProperty("value", 1.2)
        self.rasterwidth_spin.setObjectName("rasterwidth_spin")
        self.horizontalLayout_11.addWidget(self.rasterwidth_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.settings_tab)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.sigma_spin = QtWidgets.QDoubleSpinBox(self.settings_tab)
        self.sigma_spin.setMinimumSize(QtCore.QSize(0, 25))
        self.sigma_spin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sigma_spin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sigma_spin.setMinimum(0.1)
        self.sigma_spin.setMaximum(10.0)
        self.sigma_spin.setSingleStep(0.1)
        self.sigma_spin.setProperty("value", 1.0)
        self.sigma_spin.setObjectName("sigma_spin")
        self.horizontalLayout_12.addWidget(self.sigma_spin)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.savesettings_button = QtWidgets.QPushButton(self.settings_tab)
        self.savesettings_button.setObjectName("savesettings_button")
        self.verticalLayout_4.addWidget(self.savesettings_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.right_tab.addTab(self.settings_tab, "")
        self.verticalLayout_2.addWidget(self.right_tab)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.searchmax_button = QtWidgets.QPushButton(self.centralwidget)
        self.searchmax_button.setEnabled(False)
        self.searchmax_button.setMaximumSize(QtCore.QSize(300, 16777215))
        self.searchmax_button.setObjectName("searchmax_button")
        self.verticalLayout_2.addWidget(self.searchmax_button)
        self.correct_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.correct_checkBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.correct_checkBox.setObjectName("correct_checkBox")
        self.verticalLayout_2.addWidget(self.correct_checkBox)
        self.label_step_size = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_step_size.sizePolicy().hasHeightForWidth())
        self.label_step_size.setSizePolicy(sizePolicy)
        self.label_step_size.setMinimumSize(QtCore.QSize(0, 15))
        self.label_step_size.setMaximumSize(QtCore.QSize(300, 15))
        self.label_step_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step_size.setObjectName("label_step_size")
        self.verticalLayout_2.addWidget(self.label_step_size)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(100, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(-1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stepup_button = QtWidgets.QPushButton(self.frame_2)
        self.stepup_button.setMinimumSize(QtCore.QSize(30, 30))
        self.stepup_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stepup_button.setObjectName("stepup_button")
        self.horizontalLayout_14.addWidget(self.stepup_button)
        self.label_stepsize = QtWidgets.QLabel(self.frame_2)
        self.label_stepsize.setMinimumSize(QtCore.QSize(30, 0))
        self.label_stepsize.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_stepsize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_stepsize.setObjectName("label_stepsize")
        self.horizontalLayout_14.addWidget(self.label_stepsize)
        self.stepdown_button = QtWidgets.QPushButton(self.frame_2)
        self.stepdown_button.setMinimumSize(QtCore.QSize(30, 30))
        self.stepdown_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stepdown_button.setObjectName("stepdown_button")
        self.horizontalLayout_14.addWidget(self.stepdown_button)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.stage_frame = QtWidgets.QFrame(self.centralwidget)
        self.stage_frame.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_frame.sizePolicy().hasHeightForWidth())
        self.stage_frame.setSizePolicy(sizePolicy)
        self.stage_frame.setMinimumSize(QtCore.QSize(100, 90))
        self.stage_frame.setMaximumSize(QtCore.QSize(300, 200))
        self.stage_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.stage_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stage_frame.setObjectName("stage_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stage_frame)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.zdown_button = QtWidgets.QPushButton(self.stage_frame)
        self.zdown_button.setMaximumSize(QtCore.QSize(40, 50))
        self.zdown_button.setObjectName("zdown_button")
        self.gridLayout_2.addWidget(self.zdown_button, 2, 4, 1, 1)
        self.xup_button = QtWidgets.QPushButton(self.stage_frame)
        self.xup_button.setMaximumSize(QtCore.QSize(40, 50))
        self.xup_button.setObjectName("xup_button")
        self.gridLayout_2.addWidget(self.xup_button, 1, 0, 1, 1)
        self.ydown_button = QtWidgets.QPushButton(self.stage_frame)
        self.ydown_button.setMaximumSize(QtCore.QSize(40, 50))
        self.ydown_button.setObjectName("ydown_button")
        self.gridLayout_2.addWidget(self.ydown_button, 2, 1, 1, 1)
        self.xdown_button = QtWidgets.QPushButton(self.stage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xdown_button.sizePolicy().hasHeightForWidth())
        self.xdown_button.setSizePolicy(sizePolicy)
        self.xdown_button.setMaximumSize(QtCore.QSize(40, 50))
        self.xdown_button.setObjectName("xdown_button")
        self.gridLayout_2.addWidget(self.xdown_button, 1, 2, 1, 1)
        self.zup_button = QtWidgets.QPushButton(self.stage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zup_button.sizePolicy().hasHeightForWidth())
        self.zup_button.setSizePolicy(sizePolicy)
        self.zup_button.setMaximumSize(QtCore.QSize(40, 50))
        self.zup_button.setObjectName("zup_button")
        self.gridLayout_2.addWidget(self.zup_button, 0, 4, 1, 1)
        self.yup_button = QtWidgets.QPushButton(self.stage_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yup_button.sizePolicy().hasHeightForWidth())
        self.yup_button.setSizePolicy(sizePolicy)
        self.yup_button.setMaximumSize(QtCore.QSize(40, 50))
        self.yup_button.setObjectName("yup_button")
        self.gridLayout_2.addWidget(self.yup_button, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.stage_frame)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_x.sizePolicy().hasHeightForWidth())
        self.label_x.setSizePolicy(sizePolicy)
        self.label_x.setMinimumSize(QtCore.QSize(30, 0))
        self.label_x.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_13.addWidget(self.label_x)
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_y.sizePolicy().hasHeightForWidth())
        self.label_y.setSizePolicy(sizePolicy)
        self.label_y.setMinimumSize(QtCore.QSize(30, 0))
        self.label_y.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_13.addWidget(self.label_y)
        self.label_z = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_z.sizePolicy().hasHeightForWidth())
        self.label_z.setSizePolicy(sizePolicy)
        self.label_z.setMinimumSize(QtCore.QSize(30, 0))
        self.label_z.setMaximumSize(QtCore.QSize(100, 300))
        self.label_z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_z.setObjectName("label_z")
        self.horizontalLayout_13.addWidget(self.label_z)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.left_tab.setCurrentIndex(0)
        self.right_tab.setCurrentIndex(0)
        self.left_tab.currentChanged['int'].connect(MainWindow.on_lefttab_changed)
        self.scan_button.clicked.connect(MainWindow.on_start_scan_clicked)
        self.stop_button.clicked.connect(MainWindow.on_stop_clicked)
        self.reset_button.clicked.connect(MainWindow.on_reset_clicked)
        self.live_button.clicked.connect(MainWindow.on_live_clicked)
        self.searchgrid_button.clicked.connect(MainWindow.on_searchgrid_clicked)
        self.searchmax_button.clicked.connect(MainWindow.on_search_clicked)
        self.savespectra_button.clicked.connect(MainWindow.on_save_clicked)
        self.save_button.clicked.connect(MainWindow.on_saveas_clicked)
        self.dark_button.clicked.connect(MainWindow.on_dark_clicked)
        self.ref_button.clicked.connect(MainWindow.on_lamp_clicked)
        self.mean_button.clicked.connect(MainWindow.on_mean_clicked)
        self.bg_button.clicked.connect(MainWindow.on_bg_clicked)
        self.series_button.clicked.connect(MainWindow.on_series_clicked)
        self.loaddark_button.clicked.connect(MainWindow.on_loaddark_clicked)
        self.loadlamp_button.clicked.connect(MainWindow.on_loadlamp_clicked)
        self.loadbg_button.clicked.connect(MainWindow.on_loadbg_clicked)
        self.integration_time_spin.editingFinished.connect(MainWindow.on_int_time_edited)
        self.number_of_samples_spin.editingFinished.connect(MainWindow.on_number_of_samples_edited)
        self.slitwidth_spin.editingFinished.connect(MainWindow.on_slit_width_edited)
        self.grating_combobox.activated['int'].connect(MainWindow.on_grating_changed)
        self.image_combobox.activated['int'].connect(MainWindow.on_image_readout_changed)
        self.centre_wavelength_spin.editingFinished.connect(MainWindow.on_centre_wavelength_edited)
        self.exposure_time_spin.editingFinished.connect(MainWindow.on_exposure_time_edited)
        self.search_int_time_spin.editingFinished.connect(MainWindow.on_search_int_time_edited)
        self.rasterdim_spin.editingFinished.connect(MainWindow.on_rasterdim_edited)
        self.rasterwidth_spin.editingFinished.connect(MainWindow.on_rasterwidth_edited)
        self.sigma_spin.editingFinished.connect(MainWindow.on_sigma_edited)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.left_tab.setTabText(self.left_tab.indexOf(self.spec_tab), _translate("MainWindow", "Spectrometer"))
        self.left_tab.setTabText(self.left_tab.indexOf(self.cam_tab), _translate("MainWindow", "Camera"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.live_button.setText(_translate("MainWindow", "Liveview"))
        self.livedetector_button.setText(_translate("MainWindow", "Liveview Detector"))
        self.dark_button.setText(_translate("MainWindow", "Take Dark Spectrum"))
        self.bg_button.setText(_translate("MainWindow", "Take Background Spectrum"))
        self.ref_button.setText(_translate("MainWindow", "Take Reference Spectrum"))
        self.mean_button.setText(_translate("MainWindow", "Take Mean Spectrum"))
        self.series_button.setText(_translate("MainWindow", "Take Time Series"))
        self.savespectra_button.setText(_translate("MainWindow", "Save All Spectra"))
        self.save_button.setText(_translate("MainWindow", "Save regular spectrum as"))
        self.loaddark_button.setText(_translate("MainWindow", "Load Dark Spectrum"))
        self.loadlamp_button.setText(_translate("MainWindow", "Load Lamp Spectrum"))
        self.loadbg_button.setText(_translate("MainWindow", "Load Background Spectrum"))
        self.reset_button.setText(_translate("MainWindow", "Reset Internal Data"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.spectra_tab), _translate("MainWindow", "Spectra"))
        self.addpos_button.setText(_translate("MainWindow", "Add Position to List"))
        self.spangrid_button.setText(_translate("MainWindow", "Span Grid"))
        self.searchgrid_button.setText(_translate("MainWindow", "Search Max Grid"))
        self.lockin_checkBox.setText(_translate("MainWindow", "with Lock-In"))
        self.search_checkBox.setText(_translate("MainWindow", "with Search"))
        self.label_5.setText(_translate("MainWindow", "Scanning Positions"))
        self.remove_button.setText(_translate("MainWindow", "-"))
        self.clear_button.setText(_translate("MainWindow", "clear"))
        self.scan_button.setText(_translate("MainWindow", "Start Scan"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.scanning_tab), _translate("MainWindow", "Scanning"))
        self.label.setText(_translate("MainWindow", "Spectrometer Settings"))
        self.label_2.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_3.setText(_translate("MainWindow", "Number of Samples"))
        self.label_4.setText(_translate("MainWindow", "Slit Width [um]"))
        self.label_6.setText(_translate("MainWindow", "Centre Wavelength [nm]"))
        self.label_7.setText(_translate("MainWindow", "Choose Grating:"))
        self.label_15.setText(_translate("MainWindow", "Choose Image readout:"))
        self.label_9.setText(_translate("MainWindow", "Camera Settings"))
        self.label_10.setText(_translate("MainWindow", "Exposure time [ms]"))
        self.label_8.setText(_translate("MainWindow", "Search Max Settings"))
        self.label_11.setText(_translate("MainWindow", "Integration Time [ms]"))
        self.label_12.setText(_translate("MainWindow", "Raster Dimension [steps]"))
        self.label_13.setText(_translate("MainWindow", "Raster width [um]"))
        self.label_14.setText(_translate("MainWindow", "Starting Sigma [um]"))
        self.savesettings_button.setText(_translate("MainWindow", "Save Settings"))
        self.right_tab.setTabText(self.right_tab.indexOf(self.settings_tab), _translate("MainWindow", "Settings"))
        self.searchmax_button.setText(_translate("MainWindow", "Search Maximum"))
        self.correct_checkBox.setText(_translate("MainWindow", "Correct Spectrum"))
        self.label_step_size.setText(_translate("MainWindow", "Set Step Size [um]"))
        self.stepup_button.setText(_translate("MainWindow", "+"))
        self.label_stepsize.setText(_translate("MainWindow", "1.0"))
        self.stepdown_button.setText(_translate("MainWindow", "-"))
        self.zdown_button.setText(_translate("MainWindow", "z-"))
        self.xup_button.setText(_translate("MainWindow", "x+"))
        self.ydown_button.setText(_translate("MainWindow", "y-"))
        self.xdown_button.setText(_translate("MainWindow", "x-"))
        self.zup_button.setText(_translate("MainWindow", "z+"))
        self.yup_button.setText(_translate("MainWindow", "y+"))
        self.label_x.setText(_translate("MainWindow", "X: 10.0"))
        self.label_y.setText(_translate("MainWindow", "Y: 10.0"))
        self.label_z.setText(_translate("MainWindow", "Z: 10.0"))

import resources_rc
