# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(360, 435)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        SettingsDialog.setMinimumSize(QtCore.QSize(360, 435))
        SettingsDialog.setMaximumSize(QtCore.QSize(360, 435))
        SettingsDialog.setBaseSize(QtCore.QSize(360, 440))
        SettingsDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        SettingsDialog.setSizeGripEnabled(False)
        SettingsDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 400, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(SettingsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.integration_time_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.integration_time_spin.setFrame(True)
        self.integration_time_spin.setMinimum(10)
        self.integration_time_spin.setMaximum(10000)
        self.integration_time_spin.setSingleStep(10)
        self.integration_time_spin.setProperty("value", 200)
        self.integration_time_spin.setObjectName("integration_time_spin")
        self.horizontalLayout.addWidget(self.integration_time_spin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.number_of_samples_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.number_of_samples_spin.setMinimum(1)
        self.number_of_samples_spin.setMaximum(10000)
        self.number_of_samples_spin.setProperty("value", 10)
        self.number_of_samples_spin.setObjectName("number_of_samples_spin")
        self.horizontalLayout_2.addWidget(self.number_of_samples_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.search_int_time_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.search_int_time_spin.setMinimum(10)
        self.search_int_time_spin.setMaximum(10000)
        self.search_int_time_spin.setProperty("value", 300)
        self.search_int_time_spin.setObjectName("search_int_time_spin")
        self.horizontalLayout_3.addWidget(self.search_int_time_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.rasterdim_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.rasterdim_spin.setMinimum(1)
        self.rasterdim_spin.setMaximum(500)
        self.rasterdim_spin.setProperty("value", 20)
        self.rasterdim_spin.setObjectName("rasterdim_spin")
        self.horizontalLayout_4.addWidget(self.rasterdim_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.rasterwidth_spin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.rasterwidth_spin.setMinimum(0.5)
        self.rasterwidth_spin.setMaximum(20.0)
        self.rasterwidth_spin.setProperty("value", 1.2)
        self.rasterwidth_spin.setObjectName("rasterwidth_spin")
        self.horizontalLayout_5.addWidget(self.rasterwidth_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.sigma_spin = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.sigma_spin.setMinimum(0.1)
        self.sigma_spin.setMaximum(10.0)
        self.sigma_spin.setSingleStep(0.1)
        self.sigma_spin.setProperty("value", 1.0)
        self.sigma_spin.setObjectName("sigma_spin")
        self.horizontalLayout_6.addWidget(self.sigma_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.exposure_time_spin = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.exposure_time_spin.setMinimum(50)
        self.exposure_time_spin.setMaximum(1000000)
        self.exposure_time_spin.setSingleStep(10)
        self.exposure_time_spin.setProperty("value", 100000)
        self.exposure_time_spin.setObjectName("exposure_time_spin")
        self.horizontalLayout_7.addWidget(self.exposure_time_spin)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(SettingsDialog)
        self.buttonBox.accepted.connect(SettingsDialog.accept)
        self.buttonBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.label.setText(_translate("SettingsDialog", "Spectrum Settings"))
        self.label_2.setText(_translate("SettingsDialog", "Integration Time [ms]"))
        self.label_3.setText(_translate("SettingsDialog", "Number of Samples"))
        self.label_4.setText(_translate("SettingsDialog", "Search Max Settings"))
        self.label_5.setText(_translate("SettingsDialog", "Integration Time [ms]"))
        self.label_6.setText(_translate("SettingsDialog", "Raster Dimension [steps]"))
        self.label_7.setText(_translate("SettingsDialog", "Raster width [um]"))
        self.label_8.setText(_translate("SettingsDialog", "Starting Sigma [um]"))
        self.label_9.setText(_translate("SettingsDialog", "Camera Settings"))
        self.label_10.setText(_translate("SettingsDialog", "Exposure time [us]"))

